### ISSUE TITLE
showing help as default option fails

### ISSUE THREAD

**Issue by GochoMugo** [forfutureLLC/node-simple-argparse#5]
``` bash
/home/gocho/node_modules/simple-argparse/index.js:220
  this._out(output);
       ^
TypeError: undefined is not a function
    at Object.Parser.showHelp (/home/gocho/node_modules/simple-argparse/index.js:220:8)
    at Parser.parse (/home/gocho/node_modules/simple-argparse/index.js:184:19)
    at Object.<anonymous> (/home/gocho/Repos/docvy/github/server/lib/cli.js:38:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/gocho/Repos/docvy/github/server/bin/docvy-server:3:1)
```

**Comment by GochoMugo** [comment]
**FIXED IN v0.2.2**
